insert into Seller  Values(2,1,"deeptanshu");
insert into seller Values (1,1,"Anand");
Insert into SellerInventory Values (1,1,"Shampoo",10,100);
Insert into SellerInventory Values (2,1,"Shampoo",1,100);  
select * from Items;
select * from InStock;
Insert into Payment Values(1,"card","Millionaire");
Insert into Bill Values (1,1,1,5,10,1);
Insert into SellerLocation Values (1,1,"IIITD","DELHI");
Insert into SellerLocation Values (2,1,"IIITD","DELHI");
Insert into CustomerLocation Values (1,2,"HOSTEL","DELHI");
select * from CustomerLocation;
select * from Customers;
select * from Bill;
Select * from DeliverTo;
Select * from Payment;
Select * from InStock;
Select * from SellerInventory;
Update Sellerinventory set Quantity=999 where SellerId=1 and ItemId=1;
select* from delivery;
select * from DeliverTo;
select * from SellerLocation;